### ISSUE TITLE
Can't find the [ convert ] bin in your $PATH, I try to convert svg by /home/Lingchenjin/LDBlookshow/LDBlockShow/bin/svg_kit/svg2xxx.pl 

### ISSUE THREAD

**Issue by 8ling88** [BGI-shenzhen/LDBlockShow#43]
[Lingchenjin@mu01 Example2]$ ../../bin/LDBlockShow   -InVCF ../Example1/Test.vcf.gz -OutPut out -Region chr11:24100000:24200000 -InGWAS gwas.pvalue  -OutPng  -SeleVar 2
#Detected VCF File is phased file with '|', Read VCF in Phase mode
#Warning skip low Minor Allele Frequency site, and total skip allelic sites number is :11
##Start Region Cal...	 :chr11 24100000 24200000; In This Region TotalSNP Number is 7
find blocks...
sh: /home/Lingchenjin/LDBlookshow/LDBlockShow/example/Example2/../../bin/plink: Permission denied
mv: cannot stat ‘out.plink.blocks.det’: No such file or directory
gzip: out.blocks: No such file or directory
Warining: SVG module in Perl is missing, trying to loading the built-in [SVG.pm]...
Loading SVG module done
Start draw... SVG info: SNPNumber :7 , SVG (width,height) = (455,518)
convert   SVG ---> PNG ...
Can't find the [ convert ] bin in your $PATH, I try to convert svg by /home/Lingchenjin/LDBlookshow/LDBlockShow/bin/svg_kit/svg2xxx.pl 
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:13.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at org.apache.batik.ext.awt.image.GraphicsUtil.createGraphics(Unknown Source)
	at org.apache.batik.gvt.filter.GraphicsNodeRed8Bit.genRect(Unknown Source)
	at org.apache.batik.gvt.filter.GraphicsNodeRed8Bit.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.TileCacheRed.genRect(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AbstractTiledRed.drawBlockInPlace(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AbstractTiledRed.drawBlock(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AbstractTiledRed.copyToRasterByBlocks(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.AbstractTiledRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.TranslateRed.copyData(Unknown Source)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(Unknown Source)
	at org.apache.batik.gvt.renderer.StaticRenderer.repaint(Unknown Source)
	at org.apache.batik.gvt.renderer.StaticRenderer.repaint(Unknown Source)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.transcode(Unknown Source)
	at org.apache.batik.apps.rasterizer.SVGConverter.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.execute(Unknown Source)
	at org.apache.batik.apps.rasterizer.Main.main(Unknown Source)
ALL done

**Comment by hewm2008** [comment]
1  chmd  755  -R  /home/Lingchenjin/LDBlookshow/LDBlockShow/example/Example2/../../bin/
2  就是系统安一下  convert 命令。  
 【 若有root  的可以一句命令 安装好   convert 命令;     sudo apt-get install ImageMagick or sudo yum install ImageMagick】    没有再用   conda 安装 . 再没有就自己一步步安。 即可以使用如果下命令转png: convert
